### ISSUE TITLE
yarn build 报错

### ISSUE THREAD

**Issue by suikaremilia** [UnsignedInt8/wallchat#24]
yarn的时候有warning，build的时候error，是我哪里做错了么？

# node -v
v14.17.2

# yarn -v
1.22.5

root@suika:~/leavexchat-bot# yarn
yarn install v1.22.5
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
warning @postlight/mercury-parser > request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
warning @postlight/mercury-parser > postman-request > har-validator@5.1.5: this library is no longer supported
warning @postlight/mercury-parser > postman-request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning @postlight/mercury-parser > @babel/runtime-corejs2 > core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
warning @postlight/mercury-parser > url > querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
warning @postlight/mercury-parser > turndown > jsdom > left-pad@1.3.0: use String.prototype.padStart()
warning @postlight/mercury-parser > turndown > jsdom > request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
warning @postlight/mercury-parser > turndown > jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning @postlight/mercury-parser > turndown > jsdom > request > har-validator@5.1.5: this library is no longer supported
warning @postlight/mercury-parser > turndown > jsdom > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning h2m > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning tempfile > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning wechaty > raven > uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning wechaty > open-graph > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning wechaty > opencollective > babel-polyfill > core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
warning wechaty > opencollective > babel-polyfill > babel-runtime > core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
warning wechaty-puppet-wechat > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning @types/html-entities@1.3.4: This is a stub types definition. html-entities provides its own type definitions, so you do not need this installed.
warning nyc > istanbul-lib-processinfo > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning opn-cli@5.0.0: Renamed to `open-cli`.
warning opn-cli > temp-write > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning trash-cli > update-notifier > configstore > uuid@2.0.3: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning trash-cli > trash > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning trash-cli > trash > xdg-trashdir > @sindresorhus/df > execa > cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
[3/5] Fetching packages...
warning wechaty-puppet-service@0.19.4: The engine "wechaty" appears to be invalid.
warning wechaty-puppet-service@0.19.4: The engine "wechaty-puppet" appears to be invalid.
warning wechaty-puppet@0.35.3: The engine "wechaty" appears to be invalid.
warning wechaty-puppet-wechat@0.28.3: The engine "wechaty" appears to be invalid.
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "@postlight/mercury-parser > request-promise@4.2.6" has unmet peer dependency "request@^2.34".
warning "@postlight/mercury-parser > request-promise > request-promise-core@1.1.4" has unmet peer dependency "request@^2.34".
warning " > wechaty-puppet-wechat@0.28.3" has unmet peer dependency "wechaty-puppet@>=0.34".
warning " > tslint-immutable@5.5.2" has incorrect peer dependency "typescript@^2.8.0 || ^3.0.0".
[5/5] Building fresh packages...
success Saved lockfile.
Done in 67.37s.
root@suika:~/leavexchat-bot# yarn build
yarn run v1.22.5
$ scripts/wechaty && run-s clean && run-p build:*
$ trash build test
$ tsc -p tsconfig.json
$ tsc -p tsconfig.module.json
node_modules/memory-card/dist/src/memory-card.d.ts:82:5 - error TS2416: Property 'set' in type 'MemoryCard' is not assignable to the same property in base type 'AsyncMapLike<any, any>'.
  Type '<T = any>(name: string, data: T) => Promise<this>' is not assignable to type 'AsyncifyMapFunction<any, any, (key: any, value: any) => Map<any, any>>'.
    Type 'Promise<this>' is not assignable to type 'Promise<AsyncMapLike<any, any>>'.
      Type 'this' is not assignable to type 'AsyncMapLike<any, any>'.
        Type 'MemoryCard' is missing the following properties from type 'AsyncMapLike<any, any>': [Symbol.iterator], [Symbol.toStringTag]

82     set<T = any>(name: string, data: T): Promise<this>;
       ~~~

src/bot/HandleWechatMessage.ts:130:11 - error TS2322: Type 'AnimationMessage' is not assignable to type 'Message'.
  Property 'channel_chat_created' is missing in type 'AnimationMessage' but required in type 'ChannelChatCreatedMessage'.

130           sent = await ctx['replyWithAnimation']({ source: buffer }, { caption: `${nickname}` });
              ~~~~

  node_modules/typegram/message.d.ts:145:5
    145     channel_chat_created: true;
            ~~~~~~~~~~~~~~~~~~~~
    'channel_chat_created' is declared here.

src/bot/HandleWechatMessage.ts:135:7 - error TS2322: Type 'PhotoMessage' is not assignable to type 'Message'.
  Property 'channel_chat_created' is missing in type 'PhotoMessage' but required in type 'ChannelChatCreatedMessage'.

135       sent = await ctx.replyWithPhoto({ source: await image.toStream() }, { caption: nickname });
          ~~~~

  node_modules/typegram/message.d.ts:145:5
    145     channel_chat_created: true;
            ~~~~~~~~~~~~~~~~~~~~
    'channel_chat_created' is declared here.

src/bot/HandleWechatMessage.ts:140:7 - error TS2322: Type 'VideoMessage' is not assignable to type 'Message'.
  Property 'channel_chat_created' is missing in type 'VideoMessage' but required in type 'ChannelChatCreatedMessage'.

140       sent = await ctx.replyWithVideo({ source: await video.toStream() }, {
          ~~~~

  node_modules/typegram/message.d.ts:145:5
    145     channel_chat_created: true;
            ~~~~~~~~~~~~~~~~~~~~
    'channel_chat_created' is declared here.

Found 4 errors.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "build:module" exited with 2.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
root@suika:~/leavexchat-bot#

**Comment by UnsignedInt8** [comment]
尝试手动删除一些typescript声明

rm node_modules/wechaty/src/io-peer/json-rpc-peer.d.ts;
rm node_modules/memory-card/dist/src/memory-card.d.ts;

**Comment by UnsignedInt8** [comment]
现在呢，全部依赖已经更新了

**Comment by suikaremilia** [comment]
> 现在呢，全部依赖已经更新了

现在修复了
