### ISSUE TITLE
請問wechat掃碼後跳出這些訊息該如何修正

### ISSUE THREAD

**Issue by tommas7459** [UnsignedInt8/wallchat#29]
* **I'm submitting a ...**
[V] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**

07:55:15 ERR PuppetWeChatBridge onLoad() exception: Error: execute proxyWechaty(init) error: 503, init() without a ready angular env
07:55:15 WARN execute proxyWechaty(init) error: 503, init() without a ready angular env

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by okwellok** [comment]
我也遇到了同样的问题，是因为微信限制网页登陆吗？

**Comment by UnsignedInt8** [comment]
> * **I'm submitting a ...**
>   [V] bug report
>   [ ] feature request
>   [ ] question about the decisions made in the repository
>   [ ] question about how to use this project
> * **Summary**
> 
> 07:55:15 ERR PuppetWeChatBridge onLoad() exception: Error: execute proxyWechaty(init) error: 503, init() without a ready angular env 07:55:15 WARN execute proxyWechaty(init) error: 503, init() without a ready angular env
> 
> * **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

你的系统环境是什么？

**Comment by UnsignedInt8** [comment]
> 我也遇到了同样的问题，是因为微信限制网页登陆吗？

我感觉是网络方面的问题

**Comment by okwellok** [comment]
我在vps的debian和本地的arch都试过。/login扫二维码报错都是：
![2022-04-17_11-43](https://user-images.githubusercontent.com/83217712/163699503-63f0225e-5a49-4622-b595-9306665594c4.png)

**Comment by okwellok** [comment]
> > 我也遇到了同样的问题，是因为微信限制网页登陆吗？
> 
> 我感觉是网络方面的问题

搜到的Issues都是和“当前登录环境异常。为了你的帐号安全，暂时不能登录web微信。”有关的。使用注意里面虽然说已经支持所有wechat账号登陆。但[这里](https://github.com/leochen-g/wechatBot)
![图片](https://user-images.githubusercontent.com/83217712/163700000-757ac83d-9435-4e93-bf14-9af23a12ced1.png)

**Comment by UnsignedInt8** [comment]
> > > 我也遇到了同样的问题，是因为微信限制网页登陆吗？
> > 
> > 
> > 我感觉是网络方面的问题
> 
> 搜到的Issues都是和“当前登录环境异常。为了你的帐号安全，暂时不能登录web微信。”有关的。使用注意里面虽然说已经支持所有wechat账号登陆。但[这里](https://github.com/leochen-g/wechatBot) ![图片](https://user-images.githubusercontent.com/83217712/163700000-757ac83d-9435-4e93-bf14-9af23a12ced1.png)

残念
